### ISSUE TITLE
Error : Type Error not able to use profileImageUrl

### ISSUE THREAD

**Issue by wolfgunblood** [stack-auth/stack#101]
### Type Error
Was not able to use profileImageUrl because of type mismatch

profileImageUrl type
```js    
 readonly profileImageUrl: string | null;
```

Nextjs Image src type
```js    
        src?: string | undefined;
```

![Screenshot (11)](https://github.com/stack-auth/stack/assets/53962833/a09dcf0a-814f-45df-ba03-3de8e175a6b0)
![Screenshot (12)](https://github.com/stack-auth/stack/assets/53962833/5d94dbee-8918-49e8-8a11-a28d008e622d)
![Screenshot (14)](https://github.com/stack-auth/stack/assets/53962833/cd38f9e6-7d4b-4846-8bac-32c88c7e4f47)
![Screenshot (15)](https://github.com/stack-auth/stack/assets/53962833/ccda3059-9cf9-4b24-b366-33d9914cae28)

**Comment by shiv4nk4r** [comment]
On it

**Comment by shambhabya** [comment]
Can I work on this issue?

**Comment by N2D4** [comment]
This is intentional — you need some fallback image in case users have no profile picture. The easiest way to do this is with `user.profileImageUrl ?? "https://example.com/my-own-default-avatar-image.jpg"`.
