### ISSUE TITLE
Unable to Install Project Locally Following README Instructions

### ISSUE THREAD

**Issue by imran1khan** [stack-auth/stack#102]
### Description

I am unable to install the project locally despite following all the instructions provided in the README.md file. on the github

### error 
![Screenshot 2024-06-27 062619](https://github.com/stack-auth/stack/assets/107169527/03c450a2-c4f3-4891-913e-88ddedc55bff)

**Comment by sital002** [comment]
You need to seed the database first

**Comment by sujithvn** [comment]
@imran1khan  You may refer this video for the fix.
https://youtu.be/ilQSmBpd6jQ?t=3309

**Comment by fomalhautb** [comment]
Should be fixed in #108
