### ISSUE TITLE
No Open Graph Meta Tags Present

### ISSUE THREAD

**Issue by wolfgunblood** [stack-auth/stack#103]
At present no open graph meta tags are present for stack auth website

![scrnli_27_06_2024_17-09-50](https://github.com/stack-auth/stack/assets/53962833/0189aef3-d414-4fff-887e-8b32d72d9e13)

![scrnli_27_06_2024_17-10-39](https://github.com/stack-auth/stack/assets/53962833/b5217c8f-fe90-4e06-b13d-c443cb98ee7f)

**Comment by wolfgunblood** [comment]
I would like to work on this issue

**Comment by Riteshyadavanshi** [comment]
is it still opened??

**Comment by fomalhautb** [comment]
Fixed in https://github.com/stack-auth/stack/pull/125
