### ISSUE TITLE
Update README.md instruction for local build

### ISSUE THREAD

**Issue by wolfgunblood** [stack-auth/stack#104]
Many fellow contributors faced issue while building the project locally including me

![error0](https://github.com/stack-auth/stack/assets/53962833/e62a4979-44db-4e00-92e3-a6d188b01655)

![error1](https://github.com/stack-auth/stack/assets/53962833/e304d940-3a14-4dec-93ce-990af59df860)

Would suggest giving instructions for copying env variables

Seeding initial data
```js
npx prisma db seed
```

**Comment by fomalhautb** [comment]
should be fixed in #108
