### ISSUE TITLE
Problem with setting up the project locally.

### ISSUE THREAD

**Issue by Arnab2002Pal** [stack-auth/stack#106]
There are too many errors while building and running the project locally. Along with that, the documentation is not proper regarding setting up the project.
![image](https://github.com/stack-auth/stack/assets/101279242/8623746b-3f81-40ae-ae71-7eb622c2fcf9)

![image](https://github.com/stack-auth/stack/assets/101279242/cb58462b-4969-465d-ad23-796d3e9eac84)

**Comment by arnab1656** [comment]
Exactly Myself was Going to Ask the Maintainer

**Comment by wolfgunblood** [comment]
make sure you have updated the environment variables
rebuild project after 
go to apps/backend folder
Seed the data using
`npx prisma db seed`

this solve the issue

**Comment by arnab1656** [comment]
Ok lets try

**Comment by fomalhautb** [comment]
Fixed docs in https://github.com/stack-auth/stack/pull/108
