### ISSUE TITLE
Projects should not be allowed to have same name 

### ISSUE THREAD

**Issue by wolfgunblood** [stack-auth/stack#109]
I can create new projects with same name 

- Its not ideal to have same name for different projects

- It can cause sorting and project management issues

![photo_2024-06-29_17-27-35](https://github.com/stack-auth/stack/assets/53962833/8cf8e6d6-773b-4d24-85be-8bb55af9ba5c)

**Comment by PriyeshPandey2000** [comment]
@fomalhautb Would love to work on this issue .

**Comment by P-yiush07** [comment]
@wolfgunblood heyy, can i work on this ?

**Comment by fomalhautb** [comment]
The project name is just a display name, not an unique identifier. So it is fine to have two projects with the same name. We can add a warning when people creating a project with the same name though, but I think it should still be allowed.

**Comment by P-yiush07** [comment]
> The project name is just a display name, not an unique identifier. So it is fine to have two projects with the same name. We can add a warning when people creating a project with the same name though, but I think it should still be allowed.

If it is so then can i implement this thing ?

**Comment by N2D4** [comment]
@fomalhautb changed "Project Name" to "Project Display Name". I think this is enough to clarify intent — if it's still a problem, we can think about fixing this later.
