### ISSUE TITLE
No option to delete a project

### ISSUE THREAD

**Issue by wolfgunblood** [stack-auth/stack#111]
There is no option to delete a project 
![scrnli_29_06_2024_20-14-49](https://github.com/stack-auth/stack/assets/53962833/862d10e6-e871-4453-a45a-ae4ed1827068)

**Comment by imran1khan** [comment]
issue: #111
can i work on this bro

**Comment by navneetthakor** [comment]
can I work on this issue please. I really want to contribute in this project. also Let me know if you came across any other but too.
