### ISSUE TITLE
not able to delete the user

### ISSUE THREAD

**Issue by imran1khan** [stack-auth/stack#114]
here is the video

https://github.com/stack-auth/stack/assets/107169527/386c9bfc-d217-4702-bd55-501d31a3d583

**Comment by fomalhautb** [comment]
Should be fixed in #117

**Comment by imran1khan** [comment]
@fomalhautb i am sorry to say but i am facing this issue on the deployed app, please check again

**Comment by fomalhautb** [comment]
> @fomalhautb i am sorry to say but i am facing this issue on the deployed app, please check again

It will be fixed in the next release
