### ISSUE TITLE
License clarification 

### ISSUE THREAD

**Issue by mamimotu** [stack-auth/stack#115]
Hi here, about the email editor, you say its MIT that you took from other place so is it MIT, or because you edited it so now its not?
https://github.com/stack-auth/stack/tree/dev/apps/dashboard/src/components/email-editor

Also I dont understand the project, you write "open source" but set it under license that no one can really use it as open source, so whats the point

**Comment by N2D4** [comment]
The original e-mail editor library was already MIT, and the original MIT license is attached at the bottom of the file you linked, in accordance with the MIT license.

You absolutely can use it as open-source. Both MIT and AGPLv3 are accepted by [the OSI](https://opensource.org/license) and [the FSF](https://www.gnu.org/licenses/license-list.en.html) as free and open-source software licenses.
