### ISSUE TITLE
password and repeat pasword in not showing properly and lablels are not showing as well

### ISSUE THREAD

**Issue by imran1khan** [stack-auth/stack#119]
bug

### folow the insatallation [doc](https://stack-auth-preview-ceb9c3c9-2427-4343-8cf5-f6aa35362cf9.docs.buildwithfern.com/getting-started/setup) to understand this issue

signup button should have a bit different color in my openion

lable is not showing :

![Screenshot 2024-07-01 160605](https://github.com/stack-auth/stack/assets/107169527/92fcf6dc-f176-445c-aa9a-2ae7b6f0e2f9)

password and Repet password is not showing as well

https://github.com/stack-auth/stack/assets/107169527/1eb5a93e-c09c-497c-85d0-94b73aba52a4

**Comment by lingaraj2020** [comment]
please check once again, its working fine

**Comment by imran1khan** [comment]
@lingaraj2020 okey it's working now, but how?

**Comment by lingaraj2020** [comment]
just I checked my side before going through issue and informed.
