### ISSUE TITLE
Improve Error Handling in API Handlers

### ISSUE THREAD

**Issue by kfahad5607** [stack-auth/stack#141]
Currently, there is no error handling in the API handlers. When something goes wrong, the server returns an **Internal Server Error** without providing meaningful feedback to the user.

### Few Examples

1. **Adding an Existing User to a Team**

    -  Action: Attempt to add a user who is already a member of a team
    -  Result: Unique constraint fails
    -  Screenshot:
![Screenshot from 2024-07-21 18-54-33](https://github.com/user-attachments/assets/2ab01b2e-96ed-4630-b499-07aac0791d4d)

-  **Deleting a Non-Existent User from a Team**

    -  Action: Attempt to delete a user who is not in the team
    -  Result: Record does not exist
    -  Screenshot:
![image](https://github.com/user-attachments/assets/0bd57f8d-4693-4459-a1bc-b2cb58566fb8)

- **Getting User Teams with an Invalid User ID**

    -  Action: Attempt to fetch teams for an invalid user ID
    -  Result: Invalid uuid format
    -  Screenshot:
![image](https://github.com/user-attachments/assets/a5e1f46f-78f1-425f-a8d2-9041eb7708e0)

### Expected Results
The API should handle errors gracefully and return meaningful, user-friendly error messages, such as:
- For unique constraint violations: "User already exists in the team."
- For non-existent user deletions: "User not found in the team."
- For invalid user ID requests: "Invalid user ID."

### Additional Notes
These are just a few examples of the endpoints affected. There are many more endpoints that currently lack proper error handling.

**I would love to work on this issue. Please assign it to me if possible.**

**Comment by fomalhautb** [comment]
Hey thanks for reporting, we are actively fixing this issue now!

**Comment by kfahad5607** [comment]
I would be more than happy to help in any way I can and would appreciate being assigned tasks.

**Comment by kumarvinayak490** [comment]
I would be happy to work on this issue and implement best error handling practices going on in the industry. Looking forward to hearing from you

**Comment by N2D4** [comment]
Thanks for reporting this @kfahad5607 ! I assigned you to the issue, let me know if you're no longer interested in it

**Comment by kfahad5607** [comment]
Hi @N2D4,

Thank you for assigning this issue to me. Are there any specific instructions or things I should keep in mind before I start working on it?

**Comment by kfahad5607** [comment]
### Queries Regarding Error Handling for Route Handlers

**Few endpoints already have proper error handling:**

1. **Adding an Existing User to a Team**
   ![image](https://github.com/user-attachments/assets/19cc8557-2d99-4054-b3bf-2dd4230b0607)

2. **Getting User Teams with an Invalid User ID**
   ![image](https://github.com/user-attachments/assets/8675b81b-6d2a-4fbf-8bdb-99e79ebaf650)

**However, some endpoints do not have error handling:**

1. **Deleting a Non-Existent User from a Team**
   ![image](https://github.com/user-attachments/assets/e431cf7a-a8d9-46a2-b272-18e4a1fe73e8)

**Queries:**

- Do I need to update anything in the endpoints that already have error handling?
- Should the endpoints that currently lack error handling implement it in the same manner as the existing error-handled endpoints?
