### ISSUE TITLE
"Careers" Link in Footer Redirects to Email

### ISSUE THREAD

**Issue by Ayush9026** [stack-auth/stack#154]
### Description:
In the footer section of the Stack Auth website, the "Careers" link is currently configured to open an email contact form, which is identical to the "Contact" link. This redirection is incorrect as it should direct users to a careers page where they can find job listings and application details.

**Steps to Reproduce:**

Navigate to the Stack Auth website.
Scroll down to the footer section.
Click on the "Careers" link.
Expected Behavior:
Clicking the "Careers" link should redirect users to a dedicated careers page with information about job openings and how to apply.

**Actual Behavior:**
Clicking the "Careers" link redirects users to an email contact form, similar to the "Contact" link.

**Suggested Fix:**
Please update the "Careers" link in the footer section to point to the correct URL for the careers page. If the page does not exist, please create a dedicated careers page and link it accordingly.

Screenshot:

![Stack Auth](https://github.com/user-attachments/assets/aaebae0d-f01e-448c-91b9-8405002ecb9e)

Environment:

Browser: Chrome
Operating System: Windows, Android

**Comment by fomalhautb** [comment]
This is intended, we are not hiring yet so we don't really need a "careers" page
