### ISSUE TITLE
Bug: Improper Handling of Request Body Parameters in User and Team Creation APIs

### ISSUE THREAD

**Issue by kfahad5607** [stack-auth/stack#172]
I have identified a few issues with the server APIs. Some APIs are accepting data in the request body that is not being used in the route handlers.

### 1. Create User

- **Issue**: When creating a new user, the API accepts `selected_team_id`, but the route handler does not make use of `selected_team_id`.
- ![Untitled design (1)](https://github.com/user-attachments/assets/79c0ebb2-ce10-45cc-bf7e-3777f2a0204b)

### 2. Create a Team

- **Issue**: When creating a new team, the API accepts `profile_image_url`, but the route handler does not add the `profile_image_url` to the newly created team.
- ![Untitled design](https://github.com/user-attachments/assets/dab97c71-d6f9-430c-8858-5d8afb5c73fc)

### 1. Create User

- **Solution 1**: Do not accept `selected_team_id` at all, as it does not make sense to ask for a team ID when the membership does not exist.
- **Solution 2**: Create the membership between the newly created user and `selected_team_id`, then make the team the selected team.

### 2. Create a Team

- **Solution**: Pass `profile_image_url` while creating the new team.

### Additional Notes:
**I would love to work on this issue. Please assign it to me if possible.**

**Comment by fomalhautb** [comment]
Sorry somehow missed this issue, you can work on it if you are still interested

**Comment by kfahad5607** [comment]
Yes. I am interested. Thank you.

**Comment by fomalhautb** [comment]
You can join our discord and ask me directly if you have any question or need any help

**Comment by kfahad5607** [comment]
I have already joined the discord. I will reach out if I need anything help.

**Comment by dev13-suthar** [comment]
@fomalhautb if @kfahad5607  is not working on it,  i can work on this

**Comment by kfahad5607** [comment]
Hi @dev13-suthar. Sorry to keep this fix hanging. I was busy at work but I will be creating a PR for it.
