### ISSUE TITLE
[GoodToHave] Term and Privacy page links in the signup page

### ISSUE THREAD

**Issue by deepshaswat** [stack-auth/stack#192]

**Comment by bikaxh01** [comment]
I would love to work on this issue. Please assign it to me if possible.

**Comment by N2D4** [comment]
You want to be able to supply your own terms and privacy page, and pass it into the Stack App config so it would be shown on the sign-in components?

@fomalhautb I believe you worked on something like this?

**Comment by bikaxh01** [comment]
Here is a design I have attached for your review so that I can proceed
correctly
[image: image.png]

**Comment by N2D4** [comment]
> Here is a design I have attached for your review so that I can proceed

Looks good in itself, but how would this work with OAuth providers? Will the checkbox also be required to click the "sign in with OAuth" button?

**Comment by singhsag** [comment]
I made some initial changes, it will look like below

<img width="431" alt="Screenshot 2024-08-29 at 12 56 15 PM" src="https://github.com/user-attachments/assets/31993afc-262a-4aae-9389-87a1fdea632f">

**Comment by fomalhautb** [comment]
https://github.com/stack-auth/stack/pull/227
Added here
