### ISSUE TITLE
Team Permission error

### ISSUE THREAD

**Issue by gepless** [stack-auth/stack#217]
I created a team and tried go to handler/account-settings/teams/[teamId] and got this error even though I have this permission as admin
![image](https://github.com/user-attachments/assets/f0062937-e7f7-4a85-bdcc-333ad30ae955)

**Comment by fomalhautb** [comment]
Can you try to upgrade to the newest version? I think it is already fixed

**Comment by gepless** [comment]
Unfortunatly not, updated to 2.5.28 and the error persists.

**Comment by fomalhautb** [comment]
> Unfortunatly not, updated to 2.5.28 and the error persists.

Do you have a way to reproduce this? I can't reproduce it

**Comment by fomalhautb** [comment]
I finally reproduced it. Will be fixed in the next release
