### ISSUE TITLE
Dark/Light mode not working correctly when enableColorScheme is set to false.

### ISSUE THREAD

**Issue by Chenalejandro** [stack-auth/stack#253]
Reproduction repo: https://github.com/Chenalejandro/stack-auth-theme-bug
I'm using class "dark" to change the theme of the app. When enableColorScheme is set to false in theme-provider.tsx, the dark/light mode stops working.

data-stack-theme is picking up the opposite theme:
![Screenshot from 2024-09-14 23-00-23](https://github.com/user-attachments/assets/33ebd7b9-53a8-43f6-8e39-720662cc68e6)
![Screenshot from 2024-09-14 23-00-15](https://github.com/user-attachments/assets/127463f4-b5f6-4802-8530-ed22e9f64bf0)

You can go to localhost:3000/handler/sign-in to see the bug. There is a toggle to change the theme of the app in the top left corner.

**Comment by Chenalejandro** [comment]
If I downgrade to 2.5.30, the issue is gone. The bug only occurs in versions greater than that.

**Comment by Chenalejandro** [comment]
Just noticed that stack ignores the class attribute. It first checks for color-scheme, then --background, and finally each of the `["data-joy-color-scheme", "data-mui-color-scheme", "data-theme", "data-color-scheme", "class"]`.

In my case since I'm using tailwind with css variables, the --brackground is always defined. Maybe the calculation of the luma is wrong? Or we just flip the if-else statement here? https://github.com/stack-auth/stack/blob/f8258af7aa101f02f9cb233975586bbbe366ac1b/packages/stack/src/utils/browser-script.tsx#L67

**Comment by fomalhautb** [comment]
Thanks for the detailed error report, super helpful! Fixed in this commit https://github.com/stack-auth/stack/commit/1af805e5d42e1c46c2f943b0e5154908496f2361
