### ISSUE TITLE
Can't access Stack Auth cloud with Verizon network

### ISSUE THREAD

**Issue by brianfryer** [stack-auth/stack#261]
As the title says, the auth for my web app is broken and the website stack-auth.com resolves to an error from certain IP addresses. 

The error:

![IMG_4715](https://github.com/user-attachments/assets/db603156-20eb-4fa5-95f7-99de97858fce)

I can share IP address details if those would be useful.

**Comment by fomalhautb** [comment]
Are you using Verizon? This is a known problem and we contacted Verizon already, but they are slow :(

**Comment by brianfryer** [comment]
Ahh, yes I am on a Verizon network. Thanks for letting me know!
