### ISSUE TITLE
Getting error! Not able to self host.

### ISSUE THREAD

**Issue by shinebarbhuiya** [stack-auth/stack#264]
The documentation is pretty neat but the self-hosting part is very poorly written. Wasted 5 hours and I'm getting this now 
- > pnpm run prisma generate

> @stackframe/stack-backend@2.5.37 prisma /root/stack-auth/stack/apps/backend
> pnpm run with-env prisma "generate"

> @stackframe/stack-backend@2.5.37 with-env /root/stack-auth/stack/apps/backend
> dotenv -c development -- "prisma" "generate"

Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (v5.15.0) to ./../../node_modules/.pnpm/@prisma+client@5.15.0_prisma@5.15.0/node_modules/@prisma/client in 322ms

Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```
or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
```
import { PrismaClient } from '@prisma/client/edge'
const prisma = new PrismaClient()
```

See other ways of importing Prisma Client: http://pris.ly/d/importing-client

┌─────────────────────────────────────────────────────────────┐
│  Deploying your app to serverless or edge functions?        │
│  Try Prisma Accelerate for connection pooling and caching.  │
│  https://pris.ly/cli/--accelerate                           │
└─────────────────────────────────────────────────────────────┘

┌─────────────────────────────────────────────────────────┐
│  Update available 5.15.0 -> 5.19.1                      │
│  Run the following to update                            │
│    npm i --save-dev prisma@latest                       │
│    npm i @prisma/client@latest                          │
└─────────────────────────────────────────────────────────┘

> @stackframe/stack-backend@2.5.37 generate-docs /root/stack-auth/stack/apps/backend
> pnpm run with-env tsx scripts/generate-docs.ts

> @stackframe/stack-backend@2.5.37 with-env /root/stack-auth/stack/apps/backend
> dotenv -c development -- "tsx" "scripts/generate-docs.ts"

node:internal/modules/cjs/loader:1180
  const err = new Error(`Cannot find module '${request}'`);
              ^

Error: Cannot find module '/root/stack-auth/stack/apps/backend/node_modules/@stackframe/stack-shared/dist/schema-fields.js'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:1180:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1168:15)
    at resolveExports (node:internal/modules/cjs/loader:590:14)
    at Module._findPath (node:internal/modules/cjs/loader:667:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1129:27)
    at resolve (/root/stack-auth/stack/node_modules/.pnpm/tsx@4.15.5/node_modules/tsx/dist/register-DfubRCxM.cjs:1:3084)
    at resolveRequest (/root/stack-auth/stack/node_modules/.pnpm/tsx@4.15.5/node_modules/tsx/dist/register-DfubRCxM.cjs:1:2618)
    at /root/stack-auth/stack/node_modules/.pnpm/tsx@4.15.5/node_modules/tsx/dist/register-DfubRCxM.cjs:1:3400
    at m._resolveFilename (file:///root/stack-auth/stack/node_modules/.pnpm/tsx@4.15.5/node_modules/tsx/dist/register-kaoqJ84F.mjs:1:831)
    at Module._load (node:internal/modules/cjs/loader:984:27) {
  code: 'MODULE_NOT_FOUND',
  path: '/root/stack-auth/stack/apps/backend/node_modules/@stackframe/stack-shared/package.json'
}

Node.js v20.12.2
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.

**Comment by fomalhautb** [comment]
Some one in the discord asked the same question, not sure if you are the same person. There were some mistakes in the docs and it is fixed now https://github.com/stack-auth/stack/blob/dev/docs/fern/docs/pages/others/self-host.mdx
