### ISSUE TITLE
Colorful toasts (green for success, red for error)

### ISSUE THREAD

**Issue by fomalhautb** [stack-auth/stack#270]

**Comment by Dun-sin** [comment]
Hi @fomalhautb can I take this?

**Comment by fomalhautb** [comment]
> Hi @fomalhautb can I take this?

Sure, assigned you

**Comment by Dun-sin** [comment]
@fomalhautb doesn't look like there's a way to let the toast know it's an error or a success toast.

also what about toasts that are just information?

**Comment by Jarvis-3000** [comment]
Hi @fomalhautb 
I would like to take this.
