### ISSUE TITLE
Support bold in the email text markdown editor

### ISSUE THREAD

**Issue by fomalhautb** [stack-auth/stack#298]
Similar to how the link works in the email editor

**Comment by raj17ce** [comment]
Hello @fomalhautb. Can you explain the issue in more detail? I would like to work on this.

**Comment by Jarvis-3000** [comment]
Hey @fomalhautb 

I tried to look into this issue but I think bold is already supported in every email template.
Please give more info or image for better clarification.

### I would like to work on this.

**Comment by fomalhautb** [comment]
https://github.com/stack-auth/stack/blob/efaf6db3f713f069b7dc021a6638d102ca616aa4/packages/stack-emails/src/editor/blocks/block-text.tsx#L101

This is for example how we handle hyperlinks, we need to do the same for bold text. Please consider the scenario where hyperlinks/bold text are nested/have overlap.

**Comment by raj17ce** [comment]
Hey @fomalhautb , I tried looking up on the email templates in the editor. it seems that there's already support for setting the font weight to bold. Here's an attached screenshot.
![image](https://github.com/user-attachments/assets/84f28933-ac02-4b55-9ea5-19c151ea2caf)

Let me know how should I proceed, because the issue seems to be already solved.

**Comment by fomalhautb** [comment]
> Hey @fomalhautb , I tried looking up on the email templates in the editor. it seems that there's already support for setting the font weight to bold. Here's an attached screenshot. ![image](https://private-user-images.githubusercontent.com/116947399/377344145-84f28933-ac02-4b55-9ea5-19c151ea2caf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMDk3NTgsIm5iZiI6MTcyOTIwOTQ1OCwicGF0aCI6Ii8xMTY5NDczOTkvMzc3MzQ0MTQ1LTg0ZjI4OTMzLWFjMDItNGI1NS05ZWE1LTE5YzE1MWVhMmNhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxN1QyMzU3MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zODc2MWNiMjgwZDc5YjJkOGVjNWFlNzIyNjM1NmNhMTdmMjE3Nzc4NWYwZWVkZDAwOGU1ZTFlODA4MGNhN2JhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oa8ewgVus6Ra_FcJzC_j1l2UEbiHQt56vm-jQ7XjqrQ)
> 
> Let me know how should I proceed, because the issue seems to be already solved.

Oh by bold text I mean bold a substring, like this is a **bold substring**.

**Comment by suryavirkapur** [comment]
Basically it should be format like:

`**this is some bold** this is some normal text`, right?

**Comment by fomalhautb** [comment]
> Basically it should be format like:
> 
> `**this is some bold** this is some normal text`, right?

yes

**Comment by sriharika13** [comment]
Hi @fomalhautb, I would like to work on this issue, pl assign it to me.

**Comment by Mubashirshariq** [comment]
@fomalhautb  i have raised the PR could you please suggest if there are any required
