### ISSUE TITLE
Question - How to integrate with Hubspot?

### ISSUE THREAD

**Issue by iqoOopi** [stack-auth/stack#322]
Hi there,

I'm planning to try this with hubspot private content SSO. Here is the documentation from hubspot on how to set up JWT based SSO: https://knowledge.hubspot.com/website-pages/set-up-single-sign-on-sso-to-access-private-content

In short, hubspot is asking following info so that it can get a token and read it. 
![image](https://github.com/user-attachments/assets/a317d1da-bf0c-4120-996b-148ecf71723a)

wondering where I can find these info or is it even possible for hubspot to work with stack auth?

**Comment by iqoOopi** [comment]
Another Q, does stack auth support custom branding on user login page?

**Comment by fomalhautb** [comment]
This requires us to be an OIDC identity provider, and we don't support that yet. However, we are actively working on it, stay tuned ;)
