### ISSUE TITLE
Delete team from user object from client side

### ISSUE THREAD

**Issue by ndeitch** [stack-auth/stack#336]
# Description

I'm working on to delete users' team from client side, although neither user nor team object has delete function support in the client side (`ServerTeam` type does support `team.delete()`)

I was reading the [docs](https://docs.stack-auth.com/concepts/orgs-and-teams#deleting-a-team) and it says that it should support, is the doc correct?

# Environment

- @stackframe/stack: 2.6.20
- next: 15.0.3

# How to reproduce

```tsx
'use client'

import { useUser } from '@stackframe/stack'

export default function Page() {
  const user = useUser()
  const team = user.selectedTeam
  team.delete() // Property 'delete' does not exist on type 'Team'.ts(2339)

  return <h1>Deleted</h1>
}

```

**Comment by fomalhautb** [comment]
Fixed in this commit https://github.com/stack-auth/stack/commit/da3dbd9e9b497ddc6b69e29b1433c03eacb0ab0a
