### ISSUE TITLE
BUG(stack/packages/stack/src/utils/url.tsx): Client-only `constructRedirectUrl` is called by StackServerApp 

### ISSUE THREAD

**Issue by KemingHe** [stack-auth/stack#364]
# BUG Report

## 🐛 Problem

StackServerApp is not full-server. When calling `stackServerApp.sendMagicLinkEmail`, the downstream function `constructRedirectUrl` is **client-only** and asks for `window`.

### Raw Error Output

```typescript
...
  14 | export function constructRedirectUrl(redirectUrl: URL | string | undefined) {
  15 |   const retainedQueryParams = ["after_auth_return_to"];
> 16 |   const currentUrl = new URL(window.location.href);
     |                             ^
  17 |   const url = redirectUrl ? new URL(redirectUrl, window.location.href) : new URL(window.location.href);
  18 |   for (const param of retainedQueryParams) {
...
```

### Current Status

In the Stack Auth Discord channel, we created a thread with ID: 1316094389151338587 on this issue. @fomalhautb (Zai) recommended:

> ...update it so it takes in a URL instead of reading from the window.

## 🩹 Current Workaround

Simply use `stackClientApp.sendMagicLinkEmail` on the client side. This admittedly is not a good nor permanent fix given that it disables server-side form (email) validation before sending the link.

## ⚙️ My Env 

(Not directly affecting but FYI.)

OS: Ubuntu 24 LTS
Dev: Node 22, pnpm 9.15.0
Proj: NextJS 15 with React 18, https://github.com/KemingHe/buckeye-gpt

### Client-only `constructRedirectUrl` Permalink

https://github.com/stack-auth/stack/blob/11e131fd16b3d37929ca283bba811ab8ac434913/packages/stack/src/utils/url.tsx#L14-L25

### Parent `sendMagicLinkEmail` Permalink

https://github.com/stack-auth/stack/blob/11e131fd16b3d37929ca283bba811ab8ac434913/packages/stack/src/lib/stack-app.ts#L1193-L1196

**Comment by KemingHe** [comment]
Also tagging @N2D4 seeing you are the latest author/modifier to `constructRedirectUrl`.

**Comment by N2D4** [comment]
Thanks for the report! This is being worked on in #366
