### ISSUE TITLE
Support multi-tenancy

### ISSUE THREAD

**Issue by Pramuspl** [stack-auth/stack#43]
What I'd love to see is support for multi-tenancy. I'm not sure if it'd be achievable with the organizations but for now they have very low limits of users per org. Is it a feature that you'd consider implementing?

**Comment by fomalhautb** [comment]
Hey can you elaborate a little bit on what kind of multi-tenancy do you want and what exactly do you want to do with it? Are you thinking about different login methods for different teams/organizations?

**Comment by N2D4** [comment]
If you're self-hosting, we support multi-tenancy using the concept of Projects. We also support multi-tenancy for your own apps with teams, which roughly map to what other services call Organizations. (We will later add organizations for enterprise orgs with custom sign-in methods.) Is this what you mean?

I'll close the issue now, but feel free to re-open it if you think there's something I missed in the response.
