### ISSUE TITLE
Credential login form should submit when hitting the "enter" key

### ISSUE THREAD

**Issue by smakosh** [stack-auth/stack#47]
- form should submit when hitting the "enter" key
- the inputs smh are broken that I don't see the typical password suggestion by Chrome

**Comment by soulmini** [comment]
@smakosh i can you assign to me for solving the err

**Comment by smakosh** [comment]
Only repo owners can do that @soulmini

**Comment by career-tokens** [comment]
i can help regarding the submitting the form with enter key

**Comment by N2D4** [comment]
I'll split this issue into two: This one and #56

**Comment by fomalhautb** [comment]
Will be fixed in #57

**Comment by fomalhautb** [comment]
Fixed
