### ISSUE TITLE
Feature request: avatar upload

### ISSUE THREAD

**Issue by smakosh** [stack-auth/stack#48]
would be cool to let me change my avatar here as well, not sure how their storage system works if there's any.

![image](https://github.com/stack-auth/stack/assets/20082141/a9b84648-ce28-44e1-b195-d26419290f01)

**Comment by career-tokens** [comment]
can i work on this? i will need little help with the entry parameters

**Comment by varunguleriaCodes** [comment]
Working on this @fomalhautb

**Comment by Arnab2002Pal** [comment]
@fomalhautb Hi, can we use cloud storage to store profile images because I think base64 might lead to slower queries. Just an idea before implementation
