### ISSUE TITLE
Handler component should expand to the size of the viewport

### ISSUE THREAD

**Issue by career-tokens** [stack-auth/stack#52]
![image](https://github.com/stack-auth/stack/assets/134730030/c6eaf6b8-5fa6-415b-bbba-54c8b9782ea7)

**Comment by N2D4** [comment]
@fomalhautb Thoughts on how to best fix this?

**Comment by N2D4** [comment]
We can definitely have some better defaults for cases like these though, let's keep this open for now

**Comment by career-tokens** [comment]
um I mean there are some default redirects and customising them is difficult like when you reset the password and want to come back to the login page, the default reset page appears and its UI is not good
Wouldnt it be better if the default is full page and if the user wants it then they can change the size?

**Comment by N2D4** [comment]
Should be fixed with the next release!
