### ISSUE TITLE
Credential login inputs sometimes don't show the typical password suggestion in Chrome

### ISSUE THREAD

**Issue by N2D4** [stack-auth/stack#56]
Originally reported in #47 by @smakosh

**Comment by N2D4** [comment]
@soulmini Do you still want to be assigned to this?

**Comment by soulmini** [comment]
@N2D4 yup

**Comment by fomalhautb** [comment]
After merging #57, it works with my password manager. Feel free to reopen when it happens to other password managers.

**Comment by soulmini** [comment]
@N2D4 this Issue working already no need to work on it. can you assign me other issues.
