### ISSUE TITLE
Create team button on the dashboard

### ISSUE THREAD

**Issue by N2D4** [stack-auth/stack#60]
There is no way to create a directly team on the dashboard currently

**Comment by syrok94** [comment]
hii, can I work on this?

**Comment by fomalhautb** [comment]
> hii, can I work on this?

Sure! You can join the discord if you need any help

**Comment by syrok94** [comment]
okay sure

**Comment by kabir276** [comment]
Hi! I've added an option to create teams on the dashboard's "Teams" section. I've created a pull request for your review. Please let me know if this is what you envisioned. If not, I'm happy to make further adjustments.
![0dfbfde7-05c0-4494-ac77-9c96e6c2ccf2](https://github.com/stack-auth/stack/assets/91741591/83655b99-1f8d-42c0-8c15-9dbfe0d983cc)
![441301167_400144933000193_7162136852969738185_n](https://github.com/stack-auth/stack/assets/91741591/c34b201e-9439-4a94-a4e2-992f3f0f28b2)
