### ISSUE TITLE
"Create user" button on the dashboard

### ISSUE THREAD

**Issue by N2D4** [stack-auth/stack#61]
Add a create user button on the dashboard. (only supports email/password or magic link login)

**Comment by syrok94** [comment]
hii, can I work on this?

**Comment by lu3eSkywalker** [comment]
is this still open?

**Comment by DeviSriSaiCharan** [comment]
Is this still open?

**Comment by wolfgunblood** [comment]
Is this still open ??

**Comment by N2D4** [comment]
Sorry, this is already being worked on

**Comment by VARUN-KUSH** [comment]
can i work on this issue

**Comment by Shyam3050** [comment]
is this still open

**Comment by fomalhautb** [comment]
Will be added in #173
