### ISSUE TITLE
Types: Make getUser available on StackApps without token store as long as tokenStore option is provided in the function call

### ISSUE THREAD

**Issue by N2D4** [stack-auth/stack#65]

**Comment by mit-27** [comment]
Hello @N2D4 , would love to work on this issue.

**Comment by N2D4** [comment]
> Hello @N2D4 , would love to work on this issue.

Great! I assigned you =)

**Comment by mit-27** [comment]
Hello @N2D4, could you please elaborate on this issue ? Thank you
