### ISSUE TITLE
Add a switch on dashboard to disable new signups but keep allowing logins

### ISSUE THREAD

**Issue by N2D4** [stack-auth/stack#66]

**Comment by kabir276** [comment]
On it!

**Comment by shamstabraiz** [comment]
Hello, does this still need to be done, I'm available I'm ready to start right away.

**Comment by sarvesh-official** [comment]
Hey , can you assign this task to me , I'm available and ready to contribute

**Comment by Shivam311201** [comment]
Hey, can please exactly share where you want this toggle button? Any image would work

**Comment by navneetthakor** [comment]
Hello @N2D4 I really want to solve this issue please assign it to me
